<html>
    <form id="logOnForm" action="Test2.jsp" method="POST">
        <h2>Login</h2>
        <label>UserId</label>
        <input id="UserID" name="userID" id="lUserId" type="text">
        <input type="submit" name="userRole" value="Admin">
        <input type="submit" name="userRole" value="Farmaceut">
        <input type="submit" name="userRole" value="Produktionsleder">
        <input type="submit" name="userRole" value="Laborant">
    </form>
</html>